"""Monthly range partitioning for auth_logs and tacacs_logs (PostgreSQL).

Converts the two high-volume log tables to declaratively partitioned
tables (RANGE on "timestamp", one partition per month, plus a DEFAULT
partition as a safety net). Existing rows are copied into the new
structure. The primary key becomes (id, "timestamp") — PostgreSQL
requires the partition key inside every unique constraint.

No-op on SQLite: dev/test databases keep the plain tables.

Note on SQL construction: every interpolated identifier below is a
module-level constant (table names, column lists, index names) — nothing
user-supplied ever reaches these statements. DDL cannot take bound
parameters for identifiers.

Revision ID: 0009_partition_logs
Revises:    0008_api_tokens
Create Date: 2026-07-09 16:00:00.000000
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0009_partition_logs"
down_revision: Union[str, None] = "0008_api_tokens"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_AUTH_DDL = """
CREATE TABLE auth_logs (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "timestamp"  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    username     VARCHAR(64)  NOT NULL DEFAULT '',
    mac_address  VARCHAR(17)  NOT NULL DEFAULT '',
    ip_address   VARCHAR(45)  NOT NULL DEFAULT '',
    nas_ip       VARCHAR(45)  NOT NULL DEFAULT '',
    nas_port     VARCHAR(64)  NOT NULL DEFAULT '',
    auth_method  authmethod   NOT NULL DEFAULT 'PAP',
    result       authresult   NOT NULL,
    reason       VARCHAR(255) NOT NULL DEFAULT '',
    policy_name  VARCHAR(128) NOT NULL DEFAULT '',
    vlan         INTEGER,
    session_id   VARCHAR(64)  NOT NULL DEFAULT '',
    user_id      INTEGER REFERENCES users(id),
    device_id    INTEGER REFERENCES devices(id),
    PRIMARY KEY (id, "timestamp")
) PARTITION BY RANGE ("timestamp")
"""

_AUTH_COLUMNS = (
    'id, "timestamp", username, mac_address, ip_address, nas_ip, nas_port, '
    "auth_method, result, reason, policy_name, vlan, session_id, user_id, device_id"
)

_TACACS_DDL = """
CREATE TABLE tacacs_logs (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "timestamp"     TIMESTAMPTZ      NOT NULL DEFAULT now(),
    packet_type     tacacspackettype NOT NULL,
    username        VARCHAR(64)      NOT NULL DEFAULT '',
    remote_ip       VARCHAR(45)      NOT NULL DEFAULT '',
    nas_port        VARCHAR(64)      NOT NULL DEFAULT '',
    privilege_level INTEGER          NOT NULL DEFAULT 1,
    command         TEXT             NOT NULL DEFAULT '',
    result          VARCHAR(16)      NOT NULL DEFAULT 'PASS',
    reason          VARCHAR(255)     NOT NULL DEFAULT '',
    PRIMARY KEY (id, "timestamp")
) PARTITION BY RANGE ("timestamp")
"""

_TACACS_COLUMNS = (
    'id, "timestamp", packet_type, username, remote_ip, nas_port, '
    "privilege_level, command, result, reason"
)

_INDEXES = {
    "auth_logs": ["timestamp", "username", "mac_address"],
    "tacacs_logs": ["timestamp", "username"],
}


def _month_starts(bind, old_table: str) -> list:
    """First-of-month datetimes covering existing rows plus now and next."""
    rows = bind.execute(sa.text(
        f'SELECT DISTINCT date_trunc(\'month\', "timestamp") FROM {old_table}'
    )).scalars().all()
    now = bind.execute(sa.text("SELECT date_trunc('month', now())")).scalar_one()
    nxt = bind.execute(
        sa.text("SELECT date_trunc('month', now()) + interval '1 month'")
    ).scalar_one()
    months = {m for m in rows if m is not None} | {now, nxt}
    return sorted(months)


def _convert(bind, table: str, ddl: str, columns: str) -> None:
    old = f"{table}_unpart"
    bind.execute(sa.text(f"ALTER TABLE {table} RENAME TO {old}"))
    bind.execute(sa.text(ddl))

    for month in _month_starts(bind, old):
        name = f"{table}_y{month.year:04d}m{month.month:02d}"
        bind.execute(sa.text(
            f'CREATE TABLE "{name}" PARTITION OF {table} FOR VALUES FROM '
            f"('{month.isoformat()}') TO ('{month.isoformat()}'::timestamptz "
            "+ interval '1 month')"
        ))
    bind.execute(sa.text(
        f"CREATE TABLE {table}_default PARTITION OF {table} DEFAULT"
    ))

    bind.execute(sa.text(
        f"INSERT INTO {table} ({columns}) SELECT {columns} FROM {old}"
    ))
    bind.execute(sa.text(
        f"SELECT setval(pg_get_serial_sequence('{table}', 'id'),"
        f" (SELECT COALESCE(MAX(id), 1) FROM {table}))"
    ))
    bind.execute(sa.text(f"DROP TABLE {old}"))

    for column in _INDEXES[table]:
        bind.execute(sa.text(
            f'CREATE INDEX ix_{table}_{column} ON {table} ("{column}")'
        ))


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    _convert(bind, "auth_logs", _AUTH_DDL, _AUTH_COLUMNS)
    _convert(bind, "tacacs_logs", _TACACS_DDL, _TACACS_COLUMNS)


def _revert(bind, table: str, ddl: str, columns: str) -> None:
    plain_ddl = (
        ddl.replace(') PARTITION BY RANGE ("timestamp")', ")")
           .replace('PRIMARY KEY (id, "timestamp")', "PRIMARY KEY (id)")
    )
    bind.execute(sa.text(f"ALTER TABLE {table} RENAME TO {table}_part"))
    bind.execute(sa.text(plain_ddl))
    bind.execute(sa.text(
        f"INSERT INTO {table} ({columns}) SELECT {columns} FROM {table}_part"
    ))
    bind.execute(sa.text(
        f"SELECT setval(pg_get_serial_sequence('{table}', 'id'),"
        f" (SELECT COALESCE(MAX(id), 1) FROM {table}))"
    ))
    bind.execute(sa.text(f"DROP TABLE {table}_part"))
    for column in _INDEXES[table]:
        bind.execute(sa.text(
            f'CREATE INDEX ix_{table}_{column} ON {table} ("{column}")'
        ))


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    _revert(bind, "auth_logs", _AUTH_DDL, _AUTH_COLUMNS)
    _revert(bind, "tacacs_logs", _TACACS_DDL, _TACACS_COLUMNS)
