{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "naco.secretName" . }}
  labels:
    {{- include "naco.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.values }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
